version: '3.8'

services:
  angular:
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.angular.rule=Host(`yourdomain.com`)"
      - "traefik.http.services.angular.loadbalancer.server.port=80"
    networks:
      - web

  nest:
    build: ./backend
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.yourdomain.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    networks:
      - web

networks:
  web:
    external: true
